/**
 * Token build script.
 *
 * Reads the flat theme JSON from `design-tokens/Default.tokens.json`
 * (cast-sync export format) and generates:
 *   1. A typed TypeScript theme object (`default.ts`)
 *   2. A barrel index (`index.ts`)
 *   3. A reference JSON (`default.reference.json`)
 *
 * Usage:  npx ts-node src/tokens/build.ts
 *
 * The generated files are gitignored – run this before Storybook or library
 * builds.
 */

import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Serialise a value as a TypeScript literal (strings, numbers, objects). */
function toTS(value: unknown, indent: number = 2): string {
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    const keys = Object.keys(value as Record<string, unknown>);
    if (keys.length === 0) return '{}';
    const pad = ' '.repeat(indent);
    const inner = keys
      .map(
        (k) =>
          `${pad}${/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k)}: ${toTS((value as Record<string, unknown>)[k], indent + 2)},`,
      )
      .join('\n');
    return `{\n${inner}\n${' '.repeat(indent - 2)}}`;
  }
  return String(value);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const rootDir = path.resolve(__dirname, '..', '..');
  const tokensDir = path.join(rootDir, 'design-tokens');
  const outDir = path.join(rootDir, 'src', 'tokens', 'generated');

  fs.mkdirSync(outDir, { recursive: true });

  // Read the flat token JSON (cast-sync export format)
  const filePath = path.join(tokensDir, 'Default.tokens.json');
  const raw = fs.readFileSync(filePath, 'utf-8');
  const tokens = JSON.parse(raw);

  // Build the CastTheme object from semantic + component layers
  const theme = {
    name: 'default',
    semantic: tokens.semantic,
    component: tokens.component,
  };

  // --- default.ts -----------------------------------------------------------
  const tsFile = path.join(outDir, 'default.ts');
  const tsContent = [
    '// Auto-generated by build.ts — do not edit manually.',
    "import type { CastTheme } from '../../theme/types';",
    '',
    `export const defaultTheme: CastTheme = ${toTS(theme)};`,
    '',
  ].join('\n');
  fs.writeFileSync(tsFile, tsContent);
  console.log(`  ✓ default → ${path.relative(rootDir, tsFile)}`);

  // --- default.reference.json -----------------------------------------------
  const refFile = path.join(outDir, 'default.reference.json');
  fs.writeFileSync(refFile, JSON.stringify(theme, null, 2) + '\n');
  console.log(
    `  ✓ default.reference.json → ${path.relative(rootDir, refFile)}`,
  );

  // --- index.ts (barrel) ----------------------------------------------------
  const indexFile = path.join(outDir, 'index.ts');
  const indexContent = [
    '// Auto-generated by build.ts — do not edit manually.',
    "export { defaultTheme } from './default';",
    '',
  ].join('\n');
  fs.writeFileSync(indexFile, indexContent);
  console.log('  ✓ index.ts');

  console.log('\nToken build complete.');
}

main();
